services:
  purpur:
    image: itzg/minecraft-server
    container_name: purpur
    environment:
      # Essential
      OVERRIDE_SERVER_PROPERTIES: "true"
      EULA: "true"
      ENABLE_RCON: "true"
      TYPE: PURPUR
      VERSION: "1.19"
      PURPUR_BUILD: "LATEST"
      FORCE_REDOWNLOAD: "true"
      VIEW_DISTANCE: 10
      MEMORY: 4G
      CONSOLE: "false"
      
      MOTD: "\u00a7f\u00a7lmc.cog.la"
      DIFFICULTY: normal
      OPS: "cog25"
      MAX_PLAYERS: 30

      MAX_WORLD_SIZE: 10000
      ENABLE_COMMAND_BLOCK: true
      SNOOPER_ENABLED: false
      SPAWN_PROTECTION: 3
      VIEW_DISTANCE: 12
    ports:
      - 25565:25565
    volumes:
      - ./mc:/data
    restart: unless-stopped
# volumes:
#   mc-paper: